#!/bin/bash

# =============================================================================================== #
# > The script was developed with strong POSIX concept                                            #
# =============================================================================================== #
# SUPERVISOR:    abed                         PROGRAMMER:    morris                               #
# ----------------------------------------------------------------------------------------------- #
#                                                                                                 #
# FILE:                 bsh_create_empty_db                                                       #
#                                                                                                 #
# DESCRIPTION:          This script creates empty database                                        #
#                                                                                                 #
# ARGUMENTS:                                                                                      #
#        params#        description:                                                              #
#                                                                                                 #
# INPUT FORMAT:                                                                                   #
# OUTPUT FORMAT:                                                                                  #
# IMPLEMENTATION:       bsh_create_empty_db                                                       #
#                                                                                                 #
#                                                                                                 #
# DATE:                 NAME:           MODIFICATION DESCRIPTION                                  #
#     15-05-2024            morris          Created                                               #
#                                                                                                 #
# =============================================================================================== #

# Function Declarations
# =====================

# DESCRIPTION:
# 	a description
#
# ARGUMENTS:
# 	params#			Description
# 	$1				[environment name]
#
# IMPLEMENTATION:
# 	Exit_With_Error_Internal [status error]
#
Exit_With_Error_Internal()
{
	case $1 in
		10) # init script not found
			echo "ERROR: Env init script $2 not found"
			exit $1
			;;

		11) # general error
			echo "ERROR: $1"
	        	echo "Details:"
			echo "Environment $ENV already exists. Exiting the script."
			exit $1
			;;

		*) # unknown error
			echo "ERROR: Unknown error ($1)"
			;;
	esac
}

clear
#sleep 1

# Initializations Parameters
# ==========================

# Base variables path
# -------------------
ENV="$USER"
BASE_PATH="`echo ~`"
CURR_RELATIVE_PATH="~${PWD:${#BASE_PATH}}"
FULL_PATH="$BASE_PATH/${CURR_RELATIVE_PATH:1}"
CURR_DIR="`basename $FULL_PATH`"
DB_NAME="prkdb"
DB_PATH="${DB_NAME}.db"

# Internal usage variables
# ------------------------
echo
echo "====================================================================================="
echo "~> This script creates the empty database $DB_NAME in current directory for the      "
echo "   Parking System                                                                    "
echo "====================================================================================="
#echo
echo ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ."
echo "[ENVIRONMENT: #]         ~>: $ENV"
#echo "[BASE_PATH: #]           ~>: $BASE_PATH"
echo "[CURR_RELATIVE_PATH: #]  ~>: $CURR_RELATIVE_PATH"
#echo "[FULL_PATH: #]           ~>: $FULL_PATH"
echo "[CURRENT_DIRECTORY: #]   ~>: $CURR_DIR"
echo ". . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . ."
sleep 1

## Check if a custom environment is provided
#if [ -z "$1" ] || [ $1 = $ENV ]; then
#    echo "Trying to create with the default $ENV environment."
#else
#    if [ "$1" != "$ENV" ]; then
#        echo "Trying to create with a custom $1 environment."
#    fi
#    ENV="$1"
#fi

echo
echo "$CURR_RELATIVE_PATH/"
sleep 1
#echo "$CURR_RELATIVE_PATH/$ENV"
if [ ! -f "${DB_PATH}" ]; then
	echo "For creating new $DB_NAME database you will need to be an admin"
	sudo sqlite $DB_PATH ""
	if [ -f "$DB_PATH" ]; then
		echo "The database was created: $DB_PATH"
		sudo chown $ENV:$ENV $DB_PATH
		sudo chmod 664 $DB_PATH
	else
		Exit_With_Error_Internal 
	fi
else
	echo "The database $DB_PATH already exist."
	sudo chmod 664 $DB_PATH

fi



#eval "sqlite $db_path \"\""   # WORKED
